### ISSUE TITLE
Running kinto-alwaysdata directly on an AD account

### ISSUE THREAD

**Issue by Grahack** [Kinto/kinto-alwaysdata#11]
Hi,  
I can't find any info about installing and running kinto on an AlwaysData account, except of course this project. It seems that «you're my only hope».  
I thought it could help me to understand the process but I can't extract the info from the files myself.  
Would it be possible for you to document the steps to install and run kinto on Alwaysdata?

Thanks,

**Comment by Natim** [comment]
Yes that's something we should do.

**Comment by Natim** [comment]
Hi @Grahack I wrote an article about that. http://www.servicedenuages.fr/kinto-installation-alwaysdata-manuelle

Can you try it and tell me what you think? If you don't speak french tell me and I will translate it.

**Comment by Grahack** [comment]
Je speake French grave. Merci pour l’article. Je vais tester. Je pourrais même le traduire si besoin.
