### ISSUE TITLE
'pip install -e alwaysdata_kinto' doesn't seem to install the relevant executable

### ISSUE THREAD

**Issue by Grahack** [Kinto/kinto-alwaysdata#12]
This only make `alwaysdata-kinto-worker` available, but not `alwaysdata-kinto`

NOTE: In `setup.py`, I only see the `alwaysdata-kinto-worker` console script. Is this normal?

Thanks.

**Comment by Natim** [comment]
What do you mean the relevant executable? alwaysdata-kinto-worker is the relevant executable.
If you want to use kinto-alwaysdata, just enter your credentials here: https://kinto.github.io/kinto-alwaysdata/
